language: java
include:
    - env: BUCK="build selenium-server-standalone java-small-tests chrome-test firefox-test legacy-firefox-test grid-test htmlunit-test ie-test opera-test java-small-tests"
      <<: *java
    - env: BUCK="test //java/client/test/org/openqa/selenium/atoms:test"
      <<: *java
    - env: CHROME=1 TASK="calcdeps" BUCK="test //javascript/atoms:atoms-chrome //javascript/selenium-atoms:selenium-atoms-chrome //javascript/selenium-core:selenium-core-chrome //javascript/webdriver:webdriver-chrome"
      <<: *java
      <<: *chrome

script:
- cd selenium, mvn test